name: AAAA
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Checkout lua_jeti repo
        uses: actions/checkout@v2
        with:
          repository: fazzone/lua_jeti
          path: lua_jeti
      - name: Build lua itself
        shell: bash
        run: |
          set -ex
          cd lua_jeti
          make -j4 linux
      - name: apt deps
        shell: bash
        run: "sudo apt-get install -y jq sox"
      - name: Build Lua apps
        id: lc_build
        shell: bash
        run: |
          set -ex
          lua_jeti/src/lua build/script.lua
      - name: Install bb
        shell: bash
        run: |
          set -e
          curl -L -o bb.tar.gz "https://github.com/babashka/babashka/releases/download/v1.2.174/babashka-1.2.174-linux-amd64-static.tar.gz"
          tar -xvzf bb.tar.gz
          chmod +x bb
      - name: npm deps
        shell: bash
        run: |
          npm ci
      - name: Build server jar
        shell: bash
        run: |
          ./bb clojure -M -e "(user/build-uberjar-and-exit)"
          
