name: CI
on:
  push:
    branches: [master]
jobs:
  # create_release:
  #   runs-on: ubuntu-18.04
  #   outputs:
  #     upload_url: ${{ steps.create_release.outputs.upload_url }}
  #   steps:
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: release-${{ github.run_id }}
  #         release_name: Release ${{ github.run_id }}
  #         draft: false
  #         prerelease: false
  build_and_upload:
    runs-on: ubuntu-18.04
    needs: create_release
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Checkout lua_jeti repo
        uses: actions/checkout@v2
        with:
          repository: fazzone/lua_jeti
          path: lua_jeti
      - name: Build lua
        shell: bash
        run: |
          set -ex
          cd lua_jeti
          make -j4 linux
      - name: Build LC
        shell: bash
        run: |
          set -ex
          lua_jeti/src/luac -o DFM-Maps.lc DFM-Maps.lua 
          zip -r DFM-Maps.zip  DFM-Maps.lc DFM-Maps
      - name: Upload release asset
        id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            DFM-Maps.zip




