name: CI
on:
  push:
    branches: [master]
jobs:
  create_release:
    runs-on: ubuntu-18.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          draft: false
          prerelease: false
  build_and_upload:
    runs-on: ubuntu-18.04
    needs: create_release
    steps:
      - name: checkout this repo
        uses: actions/checkout@v2
      - name: checkout lua repo
        uses: actions/checkout@v2
        with:
          repository: fazzone/lua_jeti
          path: lua_jeti
      - name: Build lua
        shell: bash
        run: |
          set -ex
          cd lua_jeti
          make -j4 linux
      - name: Build LC
        shell: bash
        run: |
          set -ex
          lua_jeti/src/luac DFM-Maps.lua
          tar -czf my_release.tar.gz README.md luac.out
      - name: Upload Release asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./my_release.tar.gz
          asset_name: output2.tar.gz
          asset_content_type: application/gzip




